# Generated by Django 5.0.6 on 2024-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_id',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(default='diploma', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id_number',
            field=models.CharField(default='9276t3', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='9284368327', max_length=20),
            preserve_default=False,
        ),
    ]
