# Generated by Django 5.0.6 on 2024-07-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_courses_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_the_week', models.DateField()),
                ('classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='courses.courses')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='courses.courses')),
            ],
        ),
    ]
