# Generated by Django 5.0.6 on 2024-07-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_class_name'),
        ('classroom_period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomperiod',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='classes.class'),
        ),
    ]
