# Generated by Django 5.0.6 on 2024-07-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_enrollment_class_number_of_enrolled_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
    ]
