# Generated by Django 5.0.6 on 2024-07-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_name',
        ),
    ]
