# Generated by Django 5.0.6 on 2024-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_bio_student_gender_student_grade_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='code',
            new_name='student_code',
        ),
        migrations.AddField(
            model_name='student',
            name='gurdian_name',
            field=models.CharField(default='mikisa n.', max_length=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_national_id_number',
            field=models.CharField(default='78326', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_next_of_kin',
            field=models.CharField(default='canary t', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.SmallIntegerField(),
        ),
    ]
