# Generated by Django 5.0.6 on 2024-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_code_student_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.TextField(default='python, kotlin, javascript'),
            preserve_default=False,
        ),
    ]
